title: Posts
description: Posts
author: 9tabs
github: https://github.com/9tabs
about: When 8 tabs isn't enough.
disqus_shortname: 9tabs-com
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/the9tabs"
    - icon: fa-github
      link: "https://github.com/9tabs"

share:
  twitter_username: the9tabs

urls:
    - text: XML Feed
      url: /feed.xml
    - text: Listicles
      url: /category/listicles
    - text: Random
      url: /category/random

url: "https://9tabs.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
